# These are supported funding model platforms

# GitHub Sponsors
# github: badhope

# Open Collective
# open_collective: badhope

# Ko-fi
# ko_fi: badhope

# Tidelift
# tidelift: tidelift/badhope

# Community Bridge
# community_bridge: badhope

# Polar
# polar: badhope

# Buy me a coffee
# buy_me_a_coffee: badhope

# Thanks.dev
# thanks_dev: badhope

# Patreon
# patreon: badhope

# Liberapay
# liberapay: badhope

# IssueHunt
# issuehunt: badhope

# LFX Crowdfunding
# lfx_crowdfunding: badhope

# Custom / one-time
# custom: ["https://example.com/donate"]
